### ISSUE TITLE
locust-grasshopper depends on very old pytest

### ISSUE THREAD

**Issue by GeorgeFischhof** [alteryx/locust-grasshopper#38]
Hi,

locust-grasshopper (1.3.20) depends on pytest (>=6.2.5,<6.3.0)
but currently (2024-04-15) pytest has a version of 8.1.1, the dependency pytest version should be raised to current.

BR,
George

**Comment by jmfiola** [comment]
@GeorgeFischhof Heyo, thanks so much for bringing this up, I've been putting this off but alas, we actually ran into this issue at alteryx so I had to fix it ahahaha. This should be fixed by https://github.com/alteryx/locust-grasshopper/pull/39. Cheers!!
