### ISSUE TITLE
Update lint checks to include ruff format check as well in the pipeline

### ISSUE THREAD

**Issue by devashish2203** [alteryx/locust-grasshopper#41]
We currently only run `ruff check .` in the PR Verification pipelines. 
We should also check formatting using `ruff format --check .`

**Comment by jmfiola** [comment]
We are using ruff in the pyproject.toml and the github pipeline, are you having any issues with it? Here's the relevant portion of the code:

[tool.ruff]
exclude = ["data-files", "docs", ".git", "__pycache__", "venv"]
src = ["src/*", "tests/unit/*"]
show-fixes = true
line-length = 88

[tool.ruff.lint]

# Adds Pyflakes, Mccabe, Pydocstyle, etc. run `ruff linter` to see all available linters
extend-select = ["F", "C90", "I", "N", "ICN"]
ignore = [ "N801", "N803", "N806", "N815", "N818", "E721"]

# Allows a single underscore to be an unused variable
dummy-variable-rgx = "^_$"

[tool.ruff.lint.mccabe]
max-complexity = 18

[tool.ruff.format]

[tool.ruff.lint.isort]
# order-by-type = false
section-order = ["future", "standard-library", "third-party", "first-party", "local-folder"]

[tool.ruff.lint.pydocstyle]
convention = "numpy"
ignore-decorators = ["property", "pytest.fixture", "locator"]

**Comment by devashish2203** [comment]
Sorry I had looked at an older pull request and saw that the Checks were still using Black etc. Updated the title to be specific to ruff format

**Comment by jmfiola** [comment]
created a PR for this: https://github.com/alteryx/locust-grasshopper/pull/42

**Comment by jmfiola** [comment]
Fixed in [1.3.23](https://github.com/alteryx/locust-grasshopper/releases/tag/v1.3.23)!
